### ISSUE TITLE
Add gateway api manifests

### ISSUE THREAD

**Issue by JuniorJPDJ** [Apollorion/manifests.io#163]
Hello!
Can you add Gateway API manifests?
The best would be if you would add all versions.

**Comment by Apollorion** [comment]
@JuniorJPDJ Im taking a vacation until Wednesday, Ill look at getting that added then :)

**Comment by Apollorion** [comment]
@JuniorJPDJ I've added it via https://github.com/Apollorion/manifests.io/pull/167. Its not part of the kubernetes spec yet, its still a CRD that would need to be installed. So its available under the `Choose a spec` dropdown via the `gatway api 1.1.0` option. https://www.manifests.io/gateway%20api/1.1.0

**Comment by JuniorJPDJ** [comment]
I see that you didn't add experimental APIs like TCPRoute or TLSRoute. Any chance to get those too?

**Comment by Apollorion** [comment]
Its supported now under `gateway api 1.1.0 experimental` https://www.manifests.io/gateway%20api/1.1.0%20experimental

**Comment by JuniorJPDJ** [comment]
Thank you very much! I appreciate the webpage very much and it's very helpful!
