### ISSUE TITLE
Add new versions of gateway-api manifests (1.2.0)

### ISSUE THREAD

**Issue by JuniorJPDJ** [Apollorion/manifests.io#191]

**Comment by Apollorion** [comment]
Hey @JuniorJPDJ Im on vacation for the next 2 weeks but Ill take a peek at this when I get back.

If you want to give it a try yourself in the meantime, adding new manifests is pretty easy.
1. Copy the CRD's into this directory: `ETL/crds`
2. Run `yarn etl`
3. Add the version to: `lib/oaspec.tsx`
4. Open a PR :)

**Comment by JuniorJPDJ** [comment]
thanks! I'll do that!
