### ISSUE TITLE
broken link for podAffinity and search in general

### ISSUE THREAD

**Issue by fvogl** [Apollorion/manifests.io#50]
When searching for affinity I get (although maybe I should not get based on the in-field docu of the search field) the list of nodeAffinity, podAffinity and podAntiAffinity which is great (actually would love to be allowed so search just everything in the search field) but those links are broken. Thought this is due to my "misuse" of the search, but also pod.spec.affinity.podAffinity is broken.

When this works with global search and all content I would definitely use it - great work!

**Comment by Apollorion** [comment]
@fvogl good catch, I can recreate this ezpz. Ill look at it tonight.

As for the search, it does expect you to search for the entire path `pod.spec.affinity.podAffinity` but I like your idea of being able to just search `podAffinity`. Im going to open a separate issue to track that as a feature request.

**Comment by Apollorion** [comment]
I've fixed it, I also noticed you can search for just `podAffinity` already as well. Maybe Im misunderstanding your use-case though?

**Comment by fvogl** [comment]
@Apollorion thanks for the fix. Regarding search I've mentioned that it does work for affinity but not for everything. You can try containers or annotations.

**Comment by Apollorion** [comment]
Ah, yeah, that makes sense. The website, currently, can only search for Resources defined in the k8s openapi spec. So if you wanted to search for `containers` you'd have to look for `container` (apposed to `containers`) as its defined as `v1.container` in the openapi spec:

https://manifests.io/k8s-1.23/container

same with `annotations`, its not a resource defined in the spec, its part of the `ObjectMeta` (metadata) resource, so you can only view it at:

https://manifests.io/k8s-1.23/ObjectMeta

Ill track this in https://github.com/Apollorion/manifests.io/issues/51 as a feature request. Thanks for your input @fvogl !!
