### ISSUE TITLE
Issue on page k8s-1.21/ValidatingWebhookConfiguration

### ISSUE THREAD

**Issue by stevep-arm** [Apollorion/manifests.io#76]
## Description of issue

> ValidatingWebhookConfiguration describes the configuration of and admission webhook that accept or reject and object without changing it. Deprecated in v1.16, planned for removal in v1.19. Use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration instead.

This looks like it was moved to v1.22 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

**Comment by Apollorion** [comment]
Thanks for reporting this, I missed this issue getting opened and I apologize.

I just updated all the kubernetes openapi specs with the latest from the kubernetes repo. Unfortunately, they are the maintainers of the spec so if its still wrong I'd suggest opening an issue with them. The specs in this repo are just mirrors of the official spec [here](https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec). They'd be the ones to maintain that.
