### ISSUE TITLE
Events Api migration

### ISSUE THREAD

**Issue by Avi-Robusta** [Apollorion/manifests.io#98]
## Description of issue
New events object since 1.19
Kubernetes docs recommends migrating to new events object available since 1.19
api group events.k8s.io
I would recommend updating the events object in 1-25, 26 and newer versions of kubernetes so users aren't confused why you have an old version there 
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25

**Comment by Apollorion** [comment]
I just updated the kubernetes open api spec for 1.23-1.27 into this repo. These files are directly copied from the official kubernetes project [here](https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec), so if its still wrong I'd open an issue with them and let them know their openapi spec needs updated for that specific version of kubernetes.
